### ISSUE TITLE
Street Address are short length 

### ISSUE THREAD

**Issue by dani00001** [mikeberger/borg_calendar#123] opened 2021-05-09 10:48 UTC
Description: In Address book , you can write on only 40 letters in street address box and it require more letters space to write in street address box.

Step to Reproduce:
1) Select and open Address book
2) Add Address book entry
3) Write street address with multiple letters and space.

Expected Result:
It require 100 letters length for street address box

Actual Result:
you can write only 40 letters in street address box 

Screenshot:
![bug1](https://user-images.githubusercontent.com/83835442/117568789-d999e500-b0db-11eb-9614-b2c3e2a2372f.png)

**Comment by mikeberger** [comment] 2021-05-12 14:25
duplicate of #89

**Closed by mikeberger** 2021-05-12 14:25 UTC
