### ISSUE TITLE
Input in field  are limited OR restricted in Address Book 

### ISSUE THREAD

**Issue by Hamadullah3592** [mikeberger/borg_calendar#114] opened 2021-05-08 21:12 UTC
**Description:**
In Address Book Input Field Are restricted Or Limited to Input The String Like If We pick the Name Field to Input Name You can't able to input more than 25 letters including special characters And if you fill the address field  you can't input 40 letters 

**Steps to reproduce:**
> GO TO Navigation Bar
> Click On Action
> Click On Address Book 
> Write in the name OR address field 

**Expected result:**
The Field are limitless if the Address and name are more than limit it must be allow to write. 

**Screenshots:**
<img width="956" alt="bug 6" src="https://user-images.githubusercontent.com/73606257/117553565-c18a7d00-b06b-11eb-9909-3ca76563891d.PNG">

**Comment by mikeberger** [comment] 2021-05-12 14:24
duplicate of issue #89

**Closed by mikeberger** 2021-05-12 14:24 UTC
