### ISSUE TITLE
Not Responding Delete One only Button 

### ISSUE THREAD

**Issue by dani00001** [mikeberger/borg_calendar#124] opened 2021-05-09 10:56 UTC
Description: Delete One Only button shows no response at its click and not deleting, it is useless when we already have delete button in menu. 

Step to Reproduce:
1) Click calendar  
2) Make new APPT 
3) Click on delete one only button

Expected Result: It requires to perform an action of deletion and displayed a message in a pop-up window.

Actual Result:
No Action perform of only one delete.

Screenshot:
![bug 2-3](https://user-images.githubusercontent.com/83835442/117569253-3bf3e500-b0de-11eb-8667-32004e42dd54.png)

**Comment by mikeberger** [comment] 2021-05-12 14:29
duplicate of #115

**Closed by mikeberger** 2021-05-12 14:29 UTC
