### ISSUE TITLE
When using the Appointment Editor, user is not prompted to save unsaved changes

### ISSUE THREAD

**Issue by gaglanicse03019** [mikeberger/borg_calendar#26] opened 2015-01-29 22:19 UTC
**Description:**
------------------------------------------
BORG Calendar's Appointment Editor does not prompt the user to save unsaved changes made to Appointments. 

For example, if the Subject (or any other field) is changed in the Appointment Editor, and then the user forgets to click the Save button, and clicks another Appointment in the Appointment List (right side of screen), the changes made to the previous Appointment will not have been saved. 

Another example is when a new Appointment is created and the Appointment Editor tab is closed prior to saving the Appointment, the user is not prompted to save the new Appointment.

**Steps to reproduce:**
------------------------------------------
	1. Start BORG Calendar 1.8.1
	2. Go to the Month View and Right-click an existing Appointment and select Edit from the context menu.
	3. Within the newly opened Appointment Editor, make changes to the Appointment. For instance, change the Subject of the Appointment.
	4. From the Appointment List section on the right side, select another Appointment (the other Appointment can exist on a different date). Note that you are not prompted to save the unsaved changes.
	5. Re-open the Appointment from Step 2; the changes made in Step 3 will not have been saved.

**Suggested Fix:**
------------------------------------------
When the Appointment editor is changed to a different Appointment or is closed, the user should be prompted about whether they would like to save the changes they have made to the Appointment.
		
**Environment:**
------------------------------------------
**Primary test environment:**
   *BORG - Berger-Organizer 1.8.1
   Build Time: 2015-01-17 14:51:28
   Java 1.7.0_65
   Ubuntu 14.04 LTS x86-64
   Macbook Pro 13" (Intel Core i5-2415M)*

**Secondary test environment:**
   *BORG - Berger-Organizer 1.8.1
   Build Time: 2015-01-17 14:51:28
   Java 1.7.0_65
   Windows 8 x86-64
   Lenovo Yoga 2 Pro (Intel Core i7-4510U)*

**Other info:**
------------------------------------------
Severity: Low

**Comment by mikeberger** [comment] 2015-02-02 00:30
duplicate of sourceforge #284

**Closed by mikeberger** 2015-02-02 00:30 UTC
Labels: duplicate
