### ISSUE TITLE
Irresponsive search button

### ISSUE THREAD

**Issue by Anees-UrRehman** [mikeberger/borg_calendar#131] opened 2021-05-10 18:20 UTC
Description:
The Search Button Is Not responding.

Steps to reproduce:

GO TO Navigation Bar
Click On Search
Click On Search String
Write in Search String Column That you want to search
Click On Search Button

Expected result:
Search button should give result we are searching for.

Screenshot one shows, I have added something 
Screenshot two shows, search button is not responding
![bug 3,1](https://user-images.githubusercontent.com/83958239/117705948-8c704e80-b181-11eb-81de-49f28ca84f23.PNG)
![bug 3,2](https://user-images.githubusercontent.com/83958239/117705960-91350280-b181-11eb-8933-3c74de929ec4.PNG)

Screenshots:

**Comment by mikeberger** [comment] 2021-05-12 14:27
duplicate of #112

**Closed by mikeberger** 2021-05-12 14:27 UTC
