### ISSUE TITLE
Less Characters in Address Book

### ISSUE THREAD

**Issue by muhammaduzair866** [mikeberger/borg_calendar#117] opened 2021-05-09 09:06 UTC
**Description:**
The address characters only have 40 characters if some want to add more clear address so it cannot write it.

**Steps to reproduced:**
click on address book
write address clearly

**expected result**
write address easily 

**actual result**
In the ending of address, we don't have any characters left

**Screenshot**
![BUg-1(address bug)](https://user-images.githubusercontent.com/81010115/117566341-9df91e00-b0cf-11eb-8aac-ae31092ea8a2.PNG)

**Comment by mikeberger** [comment] 2021-05-12 14:25
duplicate of #89

**Closed by mikeberger** 2021-05-12 14:25 UTC
