### ISSUE TITLE
Save appointment deletes the input fields

### ISSUE THREAD

**Issue by ghost** [mikeberger/borg_calendar#144] opened 2021-08-10 02:37 UTC
When you "save " an event, it should not clear the input fields, that's why we have "save & close".

or at least a setting in proprieties where one can stop this ;-)

**Comment by mikeberger** [comment] 2021-08-10 13:58
"Save" does not clear the fields, it reloads the default appointment. This was a heavily requested feature, so I am hesitant to change it. "Save & Close" was added later because some users didn't want to close the tab manually.

Have you set a default appointment by entering default values and pressing "Save Defaults"?

My default appointment contains my preferred settings for Popup Reminders. I prefer all of the other fields to be cleared. I imagine that some people would also set a default color and maybe time.

**Comment by ecxod** [comment] 2021-08-10 22:06
This is of course something else if you have already discussed and decided so. 
Briefly my reason: I am always in favor that a button should only do what it says.

- Save - should only save, no other things. No matter if useful or not. In this form it should save the content of the form to the calendar. (For caldav users this should mean a syncronization with the caldav server). 
But the appointment entry should remain open. Undecided people can then add finishing touches or notices etc.
(If you want to add a new appointment immediately after the old one, you can either use the menu or double-click in the calendar).
- Save & Close - should save the entry (syncronize if caldav) and close it so you should end up in the calendar.

**Comment by RESDXChgfore9hing** [comment] 2022-09-03 04:58
so is it going to be 3 save button?do we need a dropdown?

newidea>save?
save>save and reload?
Save & Close>Save & Close.

**Comment by mikeberger** [comment] 2022-09-08 18:59
It seems like all other calendars just have a single Save option which does a Save and Close. The "problem" here is more due to it being a non-closing, multi-appointment editor, which was designed that way around 30 years ago for reasons that I forget.

Adding a third variation on something that should be a simple Save complicates things even more.

I'd prefer to make it a single appointment popup editor with only save & close, like almost all other calendars, but any change would annoy someone, so I'll leave it as is.

**Comment by mikeberger** [comment] 2022-09-08 19:04
> * For caldav users this should mean a syncronization with the caldav server).

> Save & Close - should save the entry (syncronize if caldav) 

Going out to Caldav without explicitly being asked by the user is a problem. A key use case for Borg is running without internet on a laptop or pi and then syncing later. Without internet, each sync would hang a thread for 5 minutes and then time out and error.

Also, some caldav servers can be very slow when checking for incoming changes.  So, syncing each Save one at a time might be a lot worse than waiting and syncing once when all editing is done.

**Closed by mikeberger** 2022-09-08 19:04 UTC
