### ISSUE TITLE
Java errors when installing Borg

### ISSUE THREAD

**Issue by gitthepie** [mikeberger/borg_calendar#96] opened 2020-12-18 00:08 UTC
I recently installed Borg Calendar 1.9.0.1 on Linux Mint 20 Ulyana. During installation, I got the following errors:

com.izforge.izpack.api.exception.IzPackException: An error occured
in java.lang.Thread.run() at Thread.java:834
in com.izforge.izpack.installer.unpacker.UnpackerBase.run() at UnpackerBase.java:241
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at UnpackerBase.java:319
Caused by: java.lang.NullPointerException: null
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at UnpackerBase.java:299
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at UnpackerBase.java:475
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at UnpackerBase.java:528
in com.izforge.izpack.installer.unpacker.UnpackerBase.unpack() at UnpackerBase.java:627
in com.izforge.izpack.installer.unpacker.UnpackerBase.extract() at UnpackerBase.java:673
in com.izforge.izpack.installer.unpacker.LooseFileUnpacker.unpack() at LooseFileUnpacker.java:92
in java.io.File. () at File.java:361

I had not installed my own version of Java; I ran the installer using the default Java that came with my OS (presumably OpenJDK 11). What might have caused these errors?

By the way, Borg doesn't appear to have come with an uninstaller. Is deleting ~/BORGCalendar sufficient to uninstall completely, or are other remnants left that I need to delete? I seem to remember BORG came with a shortcut and an uninstaller that could both be searched via the system menu, but I now have to resort to running BORG via the shell script.

Update: Borg wouldn't run from the run_borg.sh file in my file manager after the installation, possibly as a result of the error. So I tried to run the file from terminal to troubleshoot. I got the error "jre/bin/java: No such file or directory". Indeed, there was no such directory in ~/BORGCalendar. But then I noticed that the unpacked installer had a jre directory whose structure looked identical to the one in ~/BORGCalendar/jre, so I copied over the jre folder and Borg now runs. But am I missing anything from the installation aside from this jre folder? If the only problem was that the jre folder wasn't properly copied, I can use the current version rather than waiting for a fix. My only concern is data loss/corruption causing me to lose events I've put into the calendar.

**Comment by mikeberger** [comment] 2020-12-18 18:15
This is a duplicate of https://github.com/mikeberger/borg_calendar/issues/95

The IzPack installer can't seem to find the JRE folder to copy. Copying it manually is the workaround. That's all IzPack was supposed to do. IzPack is not my software and I don't know why it is failing (only on linux and mac). I probably will switch to a simple ZIP file distribution for linux and only use Izpack for windows.

Izpack is responsible for adding the menu items and doing the uninstall, but it doesn't do this reliably. Uninstalling would just involve removing the folder containing the program and deleting the database folder (default is ~/.borg_db).

The failure of izpack doesn't make the program less reliable, so don't worry about data loss - but ALWAYS do backups (Export) every so often just in case.

**Comment by gitthepie** [comment] 2020-12-19 02:59
Thank you for your prompt reply Mike! Based on your reply, I believe I've got a fully functional version of Borg. As long as I can continue to work around the problem, there's no rush on the IzPack fix. I leave it up to you whether to close this issue; I didn't realize there was already a duplicate.

BORG is the best calendar system I've ever used, and I hope to continue to use it in the coming years. Its single most important  feature is that it's offline; no Internet access needed, which keeps my life private. I only wish there were a copy for mobile. I did notice there's a way to export to an .ics file, so in theory it should work with other calendars until someone ports BORG to mobile right?

**Comment by mikeberger** [comment] 2020-12-19 17:32
There is no reason to port BORG to mobile. There are already so many alternatives.

I sync BORG with my own caldav server and have access to my calendar in real time on android, windows, and linux devices via multiple apps.
It's not perfect since each app meets the caldav standard in slightly different ways and doing something complicated in one app can mess up another.

In particular, I use BORG, Thunderbird Lightning, aCalendar (android), Tasks (android), Caldav-sync (android), Baikal (caldav server that can be run on cheap web hosting), Nextcloud (caldav server that I run on a raspberry pi).

**Closed** 2020-12-25 21:15 UTC
