### ISSUE TITLE
Irresponsive delete only button

### ISSUE THREAD

**Issue by Anees-UrRehman** [mikeberger/borg_calendar#129] opened 2021-05-10 18:10 UTC
Description: Delete One Only button shows no response at its click and not deleting, it is useless when we already have delete button in menu.

Step to Reproduce:

Click calendar
Make new APPT
Click on delete one only button
Expected Result: It requires to perform an action of deletion and displayed a message in a pop-up window.

Actual Result:
No Action perform of only one delete.

Screenshot:
![delete only](https://user-images.githubusercontent.com/83958239/117705018-61392f80-b180-11eb-985e-84221a52b56a.PNG)

**Comment by mikeberger** [comment] 2021-05-12 14:29
duplicate of #115

**Closed by mikeberger** 2021-05-12 14:29 UTC
